### ISSUE TITLE
Boot logo off center on A12 Rev 3

### ISSUE THREAD

**Issue by acmeplus** [Ruka-CFW/rk3128-cfw#27]
The boot logo screen is not centered on the A12 rev 3. 

This is a known issue with rev3 uboot and will be fixed in the next revision.

**Comment by snam11** [comment]
to fix he splash screen crop, the ofw dtd or whole uboot img flash is enough

**Comment by snam11** [comment]
flashing ofw uboot solved the issue with it

**Comment by adocampo** [comment]
> flashing v3 ofw uboot solved the issue.
> a new image for v3 only i suppose is needed

where did you get that? I'm dealing with the same right now

**Comment by acmeplus** [comment]
Closing ticket. Not an issue, every console needs to be flashed with the correct revision since they have different resolutions.
