### ISSUE TITLE
PS5000 L3/R3 buttons don't work

### ISSUE THREAD

**Issue by acmeplus** [Ruka-CFW/rk3128-cfw#55]
**Describe the bug**
L3/R3 buttons don't work and cannot be mapped on retroarch, ES, or any other emulator

**Custom Firmware version:** 3.0 beta 1

**Console (please complete the following information):**
 - Brand: PS
 - Model: PS5000
 - Version: All Revs
 - Mods: None

**To Reproduce**
1. Start the console
2. With RetroArch, go to Settings -> Input -> Port 1 Controls -> L3 Button (Thumb)
3. Press A to map, and try to click L3
4. Button is not recognized

**Expected behavior**
L3/R3 should be recognized

**Additional context**
Neither emulators or test controller applications from SDL or udev seem to recognize those two controls. The issue is not exclusive of the PS5000, it happens with other consoles (e.g. PocketGo S30)

**Comment by alpgarcia** [comment]
It seems these buttons could be disconnected acording to @mcerveny findings: https://github.com/Ruka-CFW/rk3128-cfw/issues/51#issuecomment-917480793

**Comment by mcerveny** [comment]
Impossible without HW mods - https://github.com/Ruka-CFW/rk3128-cfw/issues/51#issuecomment-920460276.

**Comment by acmeplus** [comment]
> Impossible without HW mods - [#51 (comment)](https://github.com/Ruka-CFW/rk3128-cfw/issues/51#issuecomment-920460276) (updated).

Thanks @mcerveny for finding why those were not working and documenting how to modify the console to get them to work.

Closing this issue.
