### ISSUE TITLE
Renaming Playlists/Writing

### ISSUE THREAD

**Issue by ThorpadoLegend** [Ruka-CFW/rk3128-cfw#58]
Release Ruka CFW Release 3.0 Beta 2 for PS5000

Whenever trying to enter writing e.g. renaming a playlist or applying certain file types for a playlist, when selecting a letter it places a lower case a before inputting the letter

**Comment by fakemaria** [comment]
As in other implementations in other handheld, virtual keyboard can´t be implemented in retroarch and search didn´t work. 
Closing as this is a bug of Retroarch.
