### ISSUE TITLE
Will this cfw work on PS7000? And if not, where can i get English language custom firmware guide for PS7000? 

### ISSUE THREAD

**Issue by abelogan** [Ruka-CFW/rk3128-cfw#63]
I'd like to pimp out my PS7000, but I can't find an English guide for the PS7000 custom firmware ANYWHERE..?

**Comment by fakemaria** [comment]
> I'd like to pimp out my PS7000, but I can't find an English guide for the PS7000 custom firmware ANYWHERE..?

Because ps7000 is not supported yet. Keep an eye on the repo from time to time and check if new updates are available ,including ps7000

**Comment by fakemaria** [comment]
> Also want try it on PS7000, thanks for what you doing

Hi! We are not supporting ps7000 in current versions. Keep looking to this repo just in case we add it in the future ;)
