### ISSUE TITLE
Support for A13 later versions

### ISSUE THREAD

**Issue by kenelm-ng** [Ruka-CFW/rk3128-cfw#64]
Hi, I heard that the later version of A13 has IPS screen and the current v3.0 Alpha 1 does not support it.
It may cause constantly crashing the system.
I don't have proof for that but just could you confirm that the new IPS screen version of A13 are not supported yet?
How do people identify the board and screen version?
Thank you.

**Comment by wujunzhai** [comment]
I want to know that can ruka-cfw  support 4.3 inch screen? can it support in later version?

**Comment by fakemaria** [comment]
> Hi, I heard that the later version of A13 has IPS screen and the current v3.0 Alpha 1 does not support it.
> It may cause constantly crashing the system.
> I don't have proof for that but just could you confirm that the new IPS screen version of A13 are not supported yet?
> How do people identify the board and screen version?
> Thank you.

It depends. For some users with IPS it works for other don’t. But I didn’t see any a13 with ips

**Comment by fakemaria** [comment]
> I want to know that can ruka-cfw support 4.3 inch screen? can it support in later version?

Only screens tht came from the manufacturer.
