### ISSUE TITLE
Ok...CFW installed on PS5000 and SD card files copied to SD card and roms loaded onto SD card, but I still can't play anything!

### ISSUE THREAD

**Issue by abelogan** [Ruka-CFW/rk3128-cfw#66]
I flashed the CFW with no errors, copied the files onto my SD card, loaded up my SD card with roms, but I can't Load Content.  When I try to Load Content, I go to my SD card, select a rom, and hit Load Archive, but I am only met with a screen that says there are no available Cores to play the rom.  It says Suggested Cores, but it doesn't have any cores listed.  I've even tried loading a Core first - I tried cores for MAME, SNES, and Megadrive - then Loading Content after Loading the Core, but I am met with the same issue as described above.  What am I doing wrong?

Also, are there any cores for Naomi (like Flycast) on this CFW?  Just wondering if I should bother adding those roms to the SD card; if there's no Core for it, I won't bother, but first, I need to get the basic stuff working (MAME, SNES, Megadrive, PCEngine, etc.)

By the way, after I found out nothing was working, I successfully used the backup.img file to return the unit to its stock firmware (ugh).

Thanks for any help.

**Comment by fakemaria** [comment]
> I flashed the CFW with no errors, copied the files onto my SD card, loaded up my SD card with roms, but I can't Load Content. When I try to Load Content, I go to my SD card, select a rom, and hit Load Archive, but I am only met with a screen that says there are no available Cores to play the rom. It says Suggested Cores, but it doesn't have any cores listed. I've even tried loading a Core first - I tried cores for MAME, SNES, and Megadrive - then Loading Content after Loading the Core, but I am met with the same issue as described above. What am I doing wrong?
> 
> Also, are there any cores for Naomi (like Flycast) on this CFW? Just wondering if I should bother adding those roms to the SD card; if there's no Core for it, I won't bother, but first, I need to get the basic stuff working (MAME, SNES, Megadrive, PCEngine, etc.)
> 
> By the way, after I found out nothing was working, I successfully used the backup.img file to return the unit to its stock firmware (ugh).
> 
> Thanks for any help.

You need to download the cores from the download section!
